### ISSUE TITLE
Missing Oxford comma...

### ISSUE THREAD

**Issue by mmathphil** [EricWay1024/Homological-Algebra-Notes#16]
...on page 77, second-last line:
![image](https://github.com/user-attachments/assets/83406ab5-b140-460b-864f-afaf1c377c63).

**Comment by EricWay1024** [comment]
Fixed. Thanks for the suggestion.

Your name will appear on the [Acknowledgements](https://github.com/EricWay1024/Homological-Algebra-Notes?tab=readme-ov-file#acknowledgements) of this repo. Please specify your preferred name, or your GitHub username will be used.
