### ISSUE TITLE
In the first line of bibliography the word "theory" is misspelled

### ISSUE THREAD

**Issue by hbghlyj** [EricWay1024/Homological-Algebra-Notes#3]
In the first line of bibliography the word "theory" is misspelled to "thoery"
![image](https://github.com/user-attachments/assets/57fb5693-4a6f-4143-9e32-640a10d7fe9d)

**Comment by EricWay1024** [comment]
Thanks for pointing out! It's now fixed. Check the latest release for the updated PDF.
