### ISSUE TITLE
Definition 2.1.7 contains typo C_1 -> C_1

### ISSUE THREAD

**Issue by JuliaScythe** [EricWay1024/Homological-Algebra-Notes#4]
https://github.com/EricWay1024/Homological-Algebra-Notes/blob/fc1830c1359f19778cb9f79d6a29a1ea588c032f/ha/1-cat.typ#L59

The definition of $f$ should probably be $C_1 \to C_2$!

**Comment by EricWay1024** [comment]
Fixed, thanks a lot for pointing out!
