### ISSUE TITLE
Example 2.7.7 contains typo in h'

### ISSUE THREAD

**Issue by JuliaScythe** [EricWay1024/Homological-Algebra-Notes#5]
![image](https://github.com/user-attachments/assets/fb44f727-d0bc-4b9b-8318-69f1434d9c70)

It's possible that I'm misunderstanding this, but surely $h'$ must be from $lim_I F \to B$, rather than to A, so that the composition in the next line makes sense?

**Comment by EricWay1024** [comment]
Yes, you're right. Thanks for the correction.

**Comment by JuliaScythe** [comment]
Thank you!!
