### ISSUE TITLE
Possible Typos

### ISSUE THREAD

**Issue by ascchrvalstr** [EricWay1024/Homological-Algebra-Notes#6]
I have found the following possible typos on the Homological Algebra lecture notes:
1. On page 4, Definition 1.1, line 1, "an abelian group with **maps** $R\times M\rightarrow M$ (called multiplication)" should be changed to "an abelian group with **a map** $R\times M\rightarrow M$ (called multiplication)", because multiplication is a single function instead of a family of functions.
2. On page 5, Definition 1.6, last line, "where only finitely many $a_x\in R$ **is** non-zero" should be changed to "where only finitely many $a_x\in R$ **are** non-zero".
3. On page 10, Notation 2.2.9, line 3, "this note **adapts** the following non-standard notation" should be changed to "this note **adopts** the following non-standard notation".
4. On page 11, Definition 2.3.1, line 2, $\pi_j:\prod_{i\in I}\rightarrow C_j$ should be changed to $\pi_j:\prod_{i\in I}\mathbf{C_i}\rightarrow C_j$.
5. On page 18, Proposition 2.7.10, line 1, "Let $L:\mathcal{A}\leftrightarrow\mathcal{B}:R$ be an adjunction **and**" should be changed to "Let $L:\mathcal{A}\leftrightarrow\mathcal{B}:R$ be an adjunction. **Then**".
6. On page 18, section 2.8 "Subobjects and Quotient Objects", line 1, "things we **already have** seen" should be changed to "things we **have already** seen".
7. On page 21, Proposition 3.1.7, line 1, "the **followings** are equivalent" should be changed to "the **following** are equivalent".
8. On page 21, proof of Proposition 3.1.7, line 1, "$\text{(3)}\Rightarrow\text{(1)}$ and $\text{(3)}\Rightarrow\text{(2)}$ **is** obvious" should be changed to "$\text{(3)}\Rightarrow\text{(1)}$ and $\text{(3)}\Rightarrow\text{(2)}$ **are** obvious".
9. On page 24, proof of Proposition 3.3.3, line 1, $\text{eq}(f,\mathbf{q})=\ker(f-g)$ should be changed to $\text{eq}(f,\mathbf{g})=\ker(f-g)$.
10. On page 26, proof of Proposition 3.4.4, line 2, "it is not **to** hard to find [...]" should be changed to "it is not **too** hard to find [...]".
11. On page 26, Remark 3.4.5, line 6, "It has all limits and colimits" should be changed to "It has all **finite** limits and colimits".
12. On page 26, Remark 3.4.5, line 11, $g=\text{colim}(g)$ should be changed to $g=\text{coim}(g)$.
13. On page 27, Remark 3.4.7, line 3, "almost all $i$" should be changed to "all but finitely many $i$" because $I$ is not assumed to be a measure space, and even if it were, it may have null sets that are not finite.
14. On page 30, proof of Lemma 3.5.14, line 9, "the universal property of **kernel**" should be changed to "the universal property of **the kernel**" or "the universal property of **kernels**".

Thank you in advance for looking into these possible typos.

**Comment by EricWay1024** [comment]
Thanks so much for reading so carefully. I can confirm all of your suggestions are valid. (Sorry for my occasional bad grammar!) Can you submit a PR? If not, I'm happy to edit these myself.

**Comment by ascchrvalstr** [comment]
Thanks for confirming. However, I am not familiar with Typst, so you are probably in a much better position to correct these typos. Thank you in advance.

**Comment by EricWay1024** [comment]
All fixed. Thanks a lot for pointing these out!

**Comment by EricWay1024** [comment]
For the record, regarding point 13, it is common in algebra texts to (informally) use 'almost all' to mean 'all but finitely many'. For example, in Lang's _Algebra_ (Revised Third Edition, p5), there is:
![image](https://github.com/user-attachments/assets/e60073af-eb1e-4183-94c9-0e96cc27e294)

In Rotman's _An Introduction to the Theory of Groups_ (Fourth Edition, p313), there is:
![image](https://github.com/user-attachments/assets/576c981d-13c2-4453-b0fc-4ea20fe12bac)

Surely, to be rigorous, we have to define this explicitly as they did, but since the wording is commonly used, I would assume people should understand 'almost all' without problems in this context.

That said, I don't mind having changed it for more clarity. Thanks for bringing this to my attention!
